### ISSUE TITLE
Add MEGA65 hardware support

### ISSUE THREAD

**Issue by amb5l** [amb5l/tyto2#4]
Further to [this issue](https://github.com/amb5l/tyto_project/issues/6) with the old repo, let's add the MEGA65 as a supported platform for the **hdmi_tpg** design (and bring in the `oserdese2` related fix).

@sy2002 How many revisions of the MEGA65 hardware do I need to consider? [TE0765-03.pdf](https://github.com/amb5l/tyto_project/files/10322033/TE0765-03.pdf) is rev 03?

**Comment by sy2002** [comment]
@amb5l Let's **only consider "Revision 3" aka R3 for now**. Reason:

* Revision 1 was only a test-board
* Revision 2 used an ADV7511 to generate the HDMI signal. Back in the days, I was not close enough to the project to really understand why Paul and Deft shelved the idea of using the ADV7511. Only 20 MEGA65 R2 were produced.
* Revision 3 "DevKit" and Revision 3A "The MEGA65" are quite identical (minor changes such as a larger core flash memory in R3A) - so in the MEGA65 community the R3 and R3A are not really distinguished and just called "R3"
*

**Comment by amb5l** [comment]
Understood. I am now working on this. I have ordered a MEGA65 from Trenz - should have done this long ago!

The ADV7511 will have consumed many I/O pins (about the same number as for VGA => VDAC) and will have been significantly more expensive than driving TMDS directly.

**Comment by sy2002** [comment]
Hey cool that you ordered a MEGA65 :-)   But here comes the bad news: You will probably need to wait until Christmas this year to get it due to "Global Chip Crisis". I recommend to join the MEGA65 discord (invitation link is in the other issue) and watch the #order-support channel there to learn more about the exact delivery date.

And thanks for your thoughts around the ADV7511.

**Comment by sy2002** [comment]
@amb5l OK - after the bad news come some good news: I contacted the MEGA65 team. The MEGA65 team would like to lend you a MEGA65 developer machine (which includes a JTAG adaptor) until your own arrives (which might be around Christmas 2023). No strings attached other than that you need sign a piece of paper that you will return the machine after yours arrives. There is no expectation that you invest a ton of time into MEGA65 development. If you you helped out with HDMI from time to time - this would be more than enough - but as said: Nobody demands that. No strings attached.

Just write an email to: deft@m-e-g-a.org and tell him who you are and that you spoke with Mirko. Deft is aware of this conversation.

For preventing any form of riot (as so many people want a MEGA65 at the moment) I will delete this message as soon as you signaled that you have read it.

**Comment by amb5l** [comment]
@sy2002: I agree. I will send the email as instructed. I assume that the machine be an R3/R3A? Likewise I will delete this message.

**Comment by sy2002** [comment]
@amb5l Yes, the machine is either a R3/R3A.

**Comment by amb5l** [comment]
Take a look at [this commit](https://github.com/amb5l/tyto2/commit/279dba69505dd01eca96cd551707f9ecd3504af7). You will find a bitstream (`hdmi_tpg_mega65r3.bit`) in `build/hdmi_tpg/hdmi_tpg_mega65r3`. At the moment this uses the joystick fire buttons - A to step the mode and B to reset. I will look at how to use the keyboard.

**Comment by amb5l** [comment]
Long since done.
